Repository NarapichasOfficial/Narapichas, pull requests merged in 2022-10, with the labels that each got.

#1 mergeSort fix
  mergeSort/mergeSort.cpp
  mergeSort/mergeSort.java
  mergeSort/mergeSort.js
  mergeSort/mergeSort.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, digitalocean

#2 Test fix
  bubbleSort/bubbleSort.java
  bubbleSort/bubbleSort.js
  bubbleSort/bubbleSort.py
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, digitalocean

#3 selectionSort fix
  selectionSort/selectionSort.java
  selectionSort/selectionSort.js
  selectionSort/selectionSort.py
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#4 Insertion sort fix
  insertionSort/insertionSort.java
  insertionSort/insertionSort.js
  insertionSort/insertionSort.py
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#5 selection sort fix
  selection sort/selectioninjava.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#6 Dynamic binding
  Dynamic binding/Dynamicbinding.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#8 Create bubblesort.c
  bubbleSort/bubblesort.c
  insertionSort/insertionsort.cpp
Labels: hacktoberfest-accepted

#7 Create sortinjava.java
  sort/arraysort.java
  sort/sortinjava.java
Labels: hacktoberfest-accepted
